from POO1 import Pessoa
#menu importando uma classe do arquivo POO1
pessoa1 = Pessoa("Carlos",78,23,False)
pessoa1.Comer("Maça")
pessoa1.Comer("banana")
pessoa1.Falar()
pessoa1.PararDeComer()
pessoa1.Falar()
pessoa1.PararDeFalar()
pessoa1.Falar()
pessoa1.Falar()
pessoa1.Comer("Feijão")
pessoa1.Comer("Laranja")
pessoa1.Falar()
pessoa1.PararDeComer()
pessoa1.Falar()
pessoa1.PararDeFalar()
pessoa1.Falar()
pessoa1.Comer("Pão")
pessoa1.Comer("Biscoito")
pessoa1.Falar()
pessoa1.PararDeComer()
pessoa1.Falar()
pessoa1.PararDeFalar()
pessoa1.Falar()
pessoa1.Comer("Uva")
pessoa1.PararDeComer()
pessoa1.Falar()


